### ISSUE TITLE
Support for build args

### ISSUE THREAD

**Issue by AlexBa** [DockStation/dockstation#121]
Hey,
would it be possible to support Docker build args? It's "new" since version 3.3.

Thank you in advance!

P.S. Dockstation is the best tool out there. It's like Mamp for Docker!

**Comment by igor-lemon** [comment]
Hi @AlexBa 
Do you mean set build args via GUI? Because if you set it args manually it should work.

**Comment by AlexBa** [comment]
Hey @igor-lemon
thank you for your fast response!

My primary problem about 1 - 1,5 weeks ago was, that Dockstation was not compatible with version Docker Compose 3.3 and upper (when I use build args). I don't know if it's fixed now. I'm using very slow 3G now and don't want to pull any image to verify it.... ;)

Build args in the GUI would be great too (if you find some time to implement this)!

**Comment by igor-lemon** [comment]
By default, DockStation supports all version of Docker Compose files because we're using your local Docker and retranslate CLI commands via GUI. v1.4.1 supports v3.3
![image](https://user-images.githubusercontent.com/14764799/40947835-85e8f568-686d-11e8-83c3-55d556e43288.png)

About adding the feature into GUI. We'll think about your propose but I'm not sure that it can be often used feature. We can to cover 100% of Compose & Docker but you will not to able work with the app because you'll not find needed stuff. We try to cover more often used things. In the next version of the app we'll add GUI editor for edit compose configs strong from app, where you can edit options which are not present at GUI. I understand that it will not resolve your issue but can help to manipulate compose configs easier, strong from the app.

**Comment by AlexBa** [comment]
Ok, thank you for your help!
