### ISSUE TITLE
Cant start projects

### ISSUE THREAD

**Issue by aequasi** [DockStation/dockstation#129]
# Bug report

## Describe the bug

Running on macOS 18.06, I can't start any projects. 

End up getting this: 
http://ss.lfgame.rs/f5ed26f978c3
http://ss.lfgame.rs/c6c000b55401

**Comment by igor-lemon** [comment]
Hi @aequasi 
Thank for the issue because it's actual problem.
A solution is very simple

1) Backup your `~/.docker/config.json` config. 
2) After need to remove this config 
`rm ~/.docker/config.json`
3) Restart Docker

Docker will create the new config with new options.

`"auths" : {
    "https://index.docker.io/v1/" : {
      "auth" : "XXX==" // Where XXX== is Base64 your login:password pair
    }
  },`
and 

`
"HttpHeaders" : {
    "User-Agent" : "Docker-Client/18.06.0-ce (darwin)" // I think you can have some other User Agent
}
`

**Comment by aequasi** [comment]
Thanks
