### ISSUE TITLE
New docker version incompatibility

### ISSUE THREAD

**Issue by x3medima17** [DockStation/dockstation#152]
Since new docker was released, URL old url format does not work.
When DockStation tries to query logs it fails with:
```
Failed to fetch container logs: 
Command failed: docker -H 127.0.0.1:3500 logs cfa82a743ba002564bd62b1d135c43e0d4a6c511b3fca27c69d614c31f3181dc --tail=1000 2>&1

[stdout]: parse 127.0.0.1:3500: first path segment in URL cannot contain colon
```

**Comment by igor-lemon** [comment]
Hi @x3medima17 Thanks for the issue. Yep, we know about this and working hard for fix it.

**Comment by x3medima17** [comment]
Cool!
Do you have any estimates? 
Really got used to use this app.

**Comment by igor-lemon** [comment]
I would make an estimate but unfortunately, I don't want to promise something because 
1) v1.5 we planned to release ~1 month ago, but during testing, we find new bugs and fix it. At the total time, we have 3 not fixed bugs (with this issue).
2) We work only a few hours per week because we're working on this project after general work. The app is free, we don't have any sponsors and we can't work fulltime on this project. I hope we resolve it problem in near future.

I can promise we'll fix this problem with high priority.

**Comment by x3medima17** [comment]
Do you have an open source codebase?
Maybe community can contribute 
In this repo I did not find any code

**Comment by igor-lemon** [comment]
No. The app is proprietary.
I've good news. We fixed this bug. Just need to wait for the new release.

**Comment by MetaiR** [comment]
@x3medima17  #144
