### ISSUE TITLE
Docker is not running

### ISSUE THREAD

**Issue by GeorgSteyn** [DockStation/dockstation#18]
Hello,
Docker is installed cleanly on a Ubuntu 16.04.2. When I installed DockStation and run it, it says docker isn't running. Though I can run docker run hello-world and get a response am I missing something.

**Comment by igor-lemon** [comment]
Hi @GeorgSteyn 
Can you run Docker as non-root user?
If not, try to do it
https://docs.docker.com/engine/installation/linux/linux-postinstall/#manage-docker-as-a-non-root-user

**Comment by GeorgSteyn** [comment]
....WOW....I feel stupid, sorry bit new to Docker still. Played around a little with it few months ago....Helps when one reads the Docs.

Sorry and Thank you for your quick response.

**Comment by igor-lemon** [comment]
You are welcome. :)

**Comment by MarkRabey-Work** [comment]
I followed those step, and am able to run `docker run hello-world` without an issue. But, I'm still getting this error. Any other suggestions?

**Comment by igor-lemon** [comment]
Hi @MarkRabey-Work
Can you give more information?
1) OS
2) Docker version and Docker Compose version

**Comment by GeorgSteyn** [comment]
Did you remember to Logout and back in again and or Restart?

**Comment by srlopez** [comment]
I can run `docker` and `dicker-compose` as my normal user, logout, resstart and stil the same message:
`Failed to attach docker event listener: Error : connect EACCES /var/run/docker.sock `
I'd like to use normal docker and not the docker-machine. 
¿What can now try?

_santi@metabook:~$_ **cat /etc/*-release**
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
_santi@metabook:~$_ **docker -v**
Docker version 17.12.1-ce, build 7390fc6
_santi@metabook:~$_ **docker-compose -v**
docker-compose version 1.17.1, build unknown

**Comment by igor-lemon** [comment]
Hi @srlopez. Can you run docker & docker-compose commands via your logged user without `sudo`?
Because I remember I could get only a version of Docker & Docker Compose without `sudo`. After running any command I had the same error. I resolved my issue with the solution that I posted above. If you can to run any command like `docker-compose up` but the app doesn't still work, let's me know about that, we'll try to find a solution.

**Comment by enriquebran** [comment]
sudo dockstation

**Comment by srlopez** [comment]
Thanks.
Solved. I made wrong Docker instalación.
Sorry

**Comment by mzenios** [comment]
Hi, 
If i do not run the dockstation as sudo, docker-compose cannot be found.
I assume this is related?
I have already access to run docker-compose without sudo, and also changed setfacl to docker.sock
Anything else i should know?

**Comment by c-thomasFR** [comment]
I have the same error on Windows

**Comment by EduardoHidalgoGarcia** [comment]
solved thanks!

**Comment by matiaslopezd** [comment]
The issue was resolve with the command suggest @enriquebran!

Copy and paste:
`sudo setfacl -m user:${USER}:rw /var/run/docker.sock`

Also, is not recommended to use docker as root, so you need to add the user to the docker group with this command `sudo usermod -aG docker ${USER}`.

`${USER}` set your current username in the command, if you want to apply to another user, change with the name.

**Comment by jonasmateus** [comment]
> `sudo dockstation`
> if you don't like execute with sudo, then:
> `sudo setfacl -m user:#usuario#:rw /var/run/docker.sock`
> 
> **#usuario#** replace with your user. Example:
> `sudo setfacl -m user:enriquebran:rw /var/run/docker.sock`

Works fine for me, thanks!
