### ISSUE TITLE
This project works with Swarm?

### ISSUE THREAD

**Issue by MichelDiz** [DockStation/dockstation#58]
I wanted to play with Swarm locally by creating three virtual machines and instantiating docker in each. Would it be possible to use Swarm with this application? It looks more robust than the kitematic.

cheers

**Comment by igor-lemon** [comment]
Hi @MichelDiz right now we don't have full support Docker Swarm. We have tools for connecting to remote nodes. We're planning to integrate Swarm and many other tools for deployment. But I can't say how soon it will be because for fast realization of a plan we need to find few payment clients or some IT companies which will support our development.
