### ISSUE TITLE
several compose files supprt

### ISSUE THREAD

**Issue by andrewkoltsov** [DockStation/dockstation#93]
for example for development I'm using dev.yml, docker-compose.yml for prod

**Comment by igor-lemon** [comment]
Hi @andrewkoltsov usually for divide we use override configs. 
1) Common
2) Override for DEV
4) Override for Prod

I think that it's better than divide to 2 configs.

**Comment by simonireilly** [comment]
I also use two separate configs and want a dockstation project for each.

Hack around this issue is to set the path to ```docker-compose.yml``` in your project as a folder with a blank file named ```docker-compose.yml```. Any file or location will do.

![image](https://user-images.githubusercontent.com/30017294/45045441-e2a0a180-b06a-11e8-9ba5-63c028448bd5.png)

Then specify the file you want as root to be the an override. This way you can select any filename you like. The blank file is loaded, then the overrides are loaded a.k.a. the file you actually want to use.

**Comment by igor-lemon** [comment]
Thanks @simonireilly for the lifehack :D
In the next v1.5, we'll go away `docker-compose.yml` naming. You'll able to set any config as a base, and as an override.
